server:
    port: 8761
spring:
    application:
        name: registry-microservice

eureka:
    # Instance properties are not needed for registry service, only in high distribution environments
#    instance:
#        hostname: localhost
#        prefer-ip-address: true
    server:
        waitTimeInMsWhenSyncEmpty: 0
    client:
        register-with-eureka: false  # No se registra a sí mismo
        fetch-registry: false        # No intenta obtener el registro de otros
        service-url:
            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/