version: '3.8'

services:
  database_dialosoft_v2:
    image: postgres:latest
    container_name: database_dialosoft_v2
    deploy:
      resources:
        limits:
          cpus: "1.5"          # El contenedor puede usar hasta 1.5 CPUs
          memory: 2G           # El contenedor puede usar hasta 2GB de RAM
        reservations:
          cpus: "0.5"          # El contenedor tiene garantizado al menos 0.5 CPUs
          memory: 1G           # El contenedor tiene garantizado al menos 1GB de RAM
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DATABASE}
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
    ports:
      - "${PORT}:${PORT_DOCKER}"
    networks:
      - dialosoft-v2-network
    # command: >
    #   bash -c "
    #     docker-entrypoint.sh postgres &
    #     sleep 10
    #     psql -U $$POSTGRES_USER -d $$POSTGRES_DB -f /docker-entrypoint-initdb.d/init-db.sql
    #     wait
    #   "
    volumes:
      - dialosoft-v2-db-data:/var/lib/postgresql/data
      - ./src/app/database/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${USER:-dialosoft_user} -d ${DATABASE:-dialosoft}" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  redis_dialosoft_v2:
    image: redis:latest
    container_name: redis_dialosoft_v2
    env_file:
      - .env
    environment:
      REDIS_PORT: ${REDIS_PORT}
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    networks:
      - dialosoft-v2-network
    volumes:
      - dialosoft-v2-redis-data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5

  # user-service:
  #   build:
  #     context: src/user-service
  #   container_name: user-service
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: "2.0"
  #         memory: 1G
  #       reservations:
  #         cpus: "1.0"
  #         memory: 512M
  #   image: dialosoft-user-service:v1.0
  #   ports:
  #     - "8086:8086"
  #     - "5007:5005"
  #   depends_on:
  #     - registry-service
  #   networks:
  #     - dialosoft-network
  #   env_file:
  #     - .env
  #   environment:
  #     HOST: ${HOST}
  #     PORT: 5432
  #     DATABASE: ${DATABASE}
  #     USER: ${USER}
  #     PASSWORD: ${PASSWORD}
  #     EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://registry-service:8761/eureka/"
  #    healthcheck:
  #      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
  #      interval: 30s
  #      timeout: 10s
  #      retries: 5
  #    command: [ "sh", "-c", "echo 'User Service ready to start' && tail -f /dev/null" ]

volumes:
  dialosoft-v2-db-data:
    name: dialosoft-v2-db-data
    driver: local
  dialosoft-v2-redis-data:
    name: dialosoft-v2-redis-data
    driver: local

networks:
  dialosoft-v2-network:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1500  # Ajusta el MTU si es necesario, MTU is the maximum transmission unit of the network
