

# APP configuration
app:
  uriServices:
    auth-microservice: http://localhost:8081
    user-microservice: http://localhost:8086
    post-manager-microservice: http://localhost:8084
    management-microservice: http://localhost:8087

# SPRING configuration

spring:
  devtools:
    restart:
      enabled: true
      # Configure the wait time between reboots
      poll-interval: 1000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# SWAGGER
springdoc:
  swagger-ui:
    urls:
      - url: /v3/api-docs
        name: API Gateway Service Swagger
        primaryName: API Gateway Service
      - url: /auth-service/v3/api-docs
        name: Auth Service Swagger
        primaryName: Auth Service Swagger
        belongServiceName: http://localhost:8081
      - url: /post-manager-service/v3/api-docs
        name: Post Manager Service Swagger
        primaryName: Post Manager Service Swagger
        belongServiceName: http://localhost:8084