
# * OVERRIDE PROPS to use

spring:
  data:
    redis:
      host: redis
      port: 6379

eureka:
  instance:
    # ${HOSTNAME} is set by Docker
    # // TODO: Check why putting with ${HOSTNAME} doesn't work with golang services
    instanceId: ${spring.application.name}:${server.port}
#    instanceId: ${spring.application.name}:${HOSTNAME}
#    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://registry-service:8761/eureka/}