
# * OVERRIDE PROPS to use

spring:
  data:
    redis:
      host: redis
      port: 6379

eureka:
  instance:
    # ${HOSTNAME} is set by Docker
    instanceId: ${spring.application.name}:${HOSTNAME}
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://registry-service:8761/eureka/}