// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "@Flussen on github",
            "email": "flussen0@gmail.com"
        },
        "license": {
            "name": "GPL-3.0 License",
            "url": "https://www.gnu.org/licenses/gpl-3.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Log in a user with username and password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Log in a user",
                "parameters": [
                    {
                        "description": "Login Request",
                        "name": "login",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Credential validation failed",
                        "schema": {
                            "$ref": "#/definitions/response.ValidatorError"
                        }
                    },
                    "401": {
                        "description": "UNAUTHORIZED",
                        "schema": {
                            "$ref": "#/definitions/response.StandardError"
                        }
                    },
                    "500": {
                        "description": "INTERNAL SERVER ERROR",
                        "schema": {
                            "$ref": "#/definitions/response.StandardError"
                        }
                    }
                }
            }
        },
        "/auth/refresh": {
            "post": {
                "description": "Refresh the access token using a refresh token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Refresh an access token",
                "parameters": [
                    {
                        "description": "Refresh Token Request",
                        "name": "refreshToken",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.RefreshToken"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.RefreshTokenResponse"
                        }
                    },
                    "400": {
                        "description": "BAD REQUEST",
                        "schema": {
                            "$ref": "#/definitions/response.StandardError"
                        }
                    },
                    "401": {
                        "description": "UNAUTHORIZED",
                        "schema": {
                            "$ref": "#/definitions/response.StandardError"
                        }
                    },
                    "500": {
                        "description": "INTERNAL SERVER ERROR",
                        "schema": {
                            "$ref": "#/definitions/response.StandardError"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Register a new user with username, email, and password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "description": "Register Request",
                        "name": "register",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.RegisterResponse"
                        }
                    },
                    "400": {
                        "description": "BAD REQUEST",
                        "schema": {
                            "$ref": "#/definitions/response.StandardError"
                        }
                    },
                    "409": {
                        "description": "CONFLICT",
                        "schema": {
                            "$ref": "#/definitions/response.StandardError"
                        }
                    },
                    "500": {
                        "description": "INTERNAL SERVER ERROR",
                        "schema": {
                            "$ref": "#/definitions/response.StandardError"
                        }
                    }
                }
            }
        },
        "/categories/create-new-category": {
            "post": {
                "security": [
                    {
                        "AccessTokenAuth": []
                    },
                    {
                        "RefreshTokenAuth": []
                    }
                ],
                "description": "Creates a new category with a specified name.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Categories"
                ],
                "summary": "Create new category",
                "parameters": [
                    {
                        "description": "New Category Data",
                        "name": "category",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.NewCategory"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "CREATED - Category created successfully",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "BAD REQUEST - Invalid input data",
                        "schema": {
                            "$ref": "#/definitions/response.StandardError"
                        }
                    },
                    "409": {
                        "description": "CONFLICT - Category already exists",
                        "schema": {
                            "$ref": "#/definitions/response.StandardError"
                        }
                    },
                    "500": {
                        "description": "INTERNAL SERVER ERROR - Unexpected server error",
                        "schema": {
                            "$ref": "#/definitions/response.StandardError"
                        }
                    }
                }
            }
        },
        "/categories/get-all-categories-allowed": {
            "get": {
                "description": "Retrieves a list of categories that the specified role is allowed to access, if is Authenticated can see protected categories by role",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Categories"
                ],
                "summary": "Get allowed categories by role",
                "responses": {
                    "200": {
                        "description": "List of accessible categories",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/response.CategoryResponse"
                            }
                        }
                    },
                    "403": {
                        "description": "FORBIDDEN - Invalid roleID format in token or unauthorized access",
                        "schema": {
                            "$ref": "#/definitions/response.StandardError"
                        }
                    },
                    "404": {
                        "description": "NOT FOUND - No categories found for this role",
                        "schema": {
                            "$ref": "#/definitions/response.StandardError"
                        }
                    },
                    "500": {
                        "description": "INTERNAL SERVER ERROR - Unexpected server error",
                        "schema": {
                            "$ref": "#/definitions/response.StandardError"
                        }
                    }
                }
            }
        },
        "/categories/protected/delete-category/{id}": {
            "delete": {
                "security": [
                    {
                        "AccessTokenAuth": []
                    },
                    {
                        "RefreshTokenAuth": []
                    }
                ],
                "description": "Deletes an existing category from the system.",
                "tags": [
                    "Categories"
                ],
                "summary": "Delete category",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Category ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "DELETED - Category deleted successfully",
                        "schema": {
                            "$ref": "#/definitions/response.StandardResponse"
                        }
                    },
                    "400": {
                        "description": "BAD REQUEST - Invalid category ID",
                        "schema": {
                            "$ref": "#/definitions/response.StandardError"
                        }
                    },
                    "404": {
                        "description": "NOT FOUND - Category not found",
                        "schema": {
                            "$ref": "#/definitions/response.StandardError"
                        }
                    },
                    "500": {
                        "description": "INTERNAL SERVER ERROR - Unexpected server error",
                        "schema": {
                            "$ref": "#/definitions/response.StandardError"
                        }
                    }
                }
            }
        },
        "/categories/protected/restore-category/{id}": {
            "put": {
                "security": [
                    {
                        "AccessTokenAuth": []
                    },
                    {
                        "RefreshTokenAuth": []
                    }
                ],
                "description": "Restores a previously deleted category.",
                "tags": [
                    "Categories"
                ],
                "summary": "Restore category",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Category ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "RESTORED - Category restored successfully",
                        "schema": {
                            "$ref": "#/definitions/response.StandardResponse"
                        }
                    },
                    "400": {
                        "description": "BAD REQUEST - Invalid category ID",
                        "schema": {
                            "$ref": "#/definitions/response.StandardError"
                        }
                    },
                    "404": {
                        "description": "NOT FOUND - Category not found",
                        "schema": {
                            "$ref": "#/definitions/response.StandardError"
                        }
                    },
                    "500": {
                        "description": "INTERNAL SERVER ERROR - Unexpected server error",
                        "schema": {
                            "$ref": "#/definitions/response.StandardError"
                        }
                    }
                }
            }
        },
        "/categories/protected/update-category/{id}": {
            "put": {
                "security": [
                    {
                        "AccessTokenAuth": []
                    },
                    {
                        "RefreshTokenAuth": []
                    }
                ],
                "description": "Updates an existing category with new data.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Categories"
                ],
                "summary": "Update category",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Category ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated Category Data",
                        "name": "category",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.NewCategory"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "UPDATED - Category updated successfully",
                        "schema": {
                            "$ref": "#/definitions/response.StandardResponse"
                        }
                    },
                    "400": {
                        "description": "BAD REQUEST - Invalid input data",
                        "schema": {
                            "$ref": "#/definitions/response.StandardError"
                        }
                    },
                    "404": {
                        "description": "NOT FOUND - Category not found",
                        "schema": {
                            "$ref": "#/definitions/response.StandardError"
                        }
                    },
                    "500": {
                        "description": "INTERNAL SERVER ERROR - Unexpected server error",
                        "schema": {
                            "$ref": "#/definitions/response.StandardError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "request.LoginRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string",
                    "example": "12345678"
                },
                "username": {
                    "type": "string",
                    "example": "matdevcoder"
                }
            }
        },
        "request.NewCategory": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "example": "some description for category 2"
                },
                "name": {
                    "type": "string",
                    "example": "Category 2"
                },
                "rolesAllowedID": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "['8213280e-2000-403a-b375-cdcda6488450'",
                        " 'roleUUID2']"
                    ]
                }
            }
        },
        "request.RefreshToken": {
            "type": "object",
            "properties": {
                "refreshToken": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                }
            }
        },
        "request.RegisterRequest": {
            "type": "object",
            "required": [
                "email",
                "password",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "busta@email.com"
                },
                "password": {
                    "type": "string",
                    "maxLength": 35,
                    "minLength": 6,
                    "example": "12345678"
                },
                "username": {
                    "type": "string",
                    "maxLength": 15,
                    "minLength": 4,
                    "example": "busta"
                }
            }
        },
        "response.CategoryResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "rolesAllowed": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "response.LoginResponse": {
            "type": "object",
            "properties": {
                "accessToken": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                },
                "refreshToken": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                }
            }
        },
        "response.RefreshTokenResponse": {
            "type": "object",
            "properties": {
                "accessToken": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                }
            }
        },
        "response.RegisterResponse": {
            "type": "object",
            "properties": {
                "accessToken": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                },
                "refreshToken": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                },
                "userID": {
                    "type": "string",
                    "example": "userID"
                }
            }
        },
        "response.StandardError": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "An error occurred - some context"
                }
            }
        },
        "response.StandardResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string",
                    "example": "info message"
                }
            }
        },
        "response.ValidatorError": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Validation failed"
                },
                "fields": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    },
                    "example": {
                        "{'username'": " 'Username is required'}"
                    }
                }
            }
        }
    },
    "securityDefinitions": {
        "AccessTokenAuth": {
            "description": "Bearer token for authentication",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        },
        "RefreshTokenAuth": {
            "description": "Refresh token for authentication",
            "type": "apiKey",
            "name": "X-Refresh-Token",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.2.0",
	Host:             "localhost:8080",
	BasePath:         "/dialosoft-api/v1",
	Schemes:          []string{},
	Title:            "Dialosoft Swagger API",
	Description:      "this is the swagger implementation for dialosoft",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
